### PR TITLE
Update drupal-ios-sdk.podspec

### PR DESCRIPTION
**Pull request by darkbreed**
You appear to have set a minimum OSX version which is unnecessary.

### CODE REVIEW

**Comment by kylebrowning** [comment]
Actually this is required for AFNetworking, im reverting it.

**Comment by glesage** [comment]
I am trying to use cocoapods to add DIOS for an iOS app.

```
platform :ios, '5.0'

pod 'FMDB'
pod 'AFNetworking'
pod 'SCNetworkReachability'
pod 'drupal-ios-sdk'
```

I get this error: `[!] The platform of the target`Pods`(iOS 5.0) is not compatible with`drupal-ios-sdk (2.0.2)`which has a minimum requirement of OS X 10.7.`

I am using AFNetworking in many apps through cocoapods, is this OSX version really required for AFNetworking?

**Comment by kylebrowning** [comment]
Im not sure how to fix it because technically the Drupal iOS SDK isnt iOS specific.  It works on OS X as well. haha.

Hrmm, not sure what to do.

**Comment by glesage** [comment]
There is a way to do multi-platforms with cocoapods: http://docs.cocoapods.org/specification.html#group_multi_platform_support

And you can also set different deployment targets for each platforms http://docs.cocoapods.org/specification.html#deployment_target

(:

**Comment by kylebrowning** [comment]
Fixed. 

https://github.com/CocoaPods/Specs/pull/2798

**Comment by glesage** [comment]
Sweet thks!

**Pull request merged**
