### PR TITLE
6.x 2.x

### PR DESCRIPTION
**Pull request by RasputinJones2k**
Hey Kyle - 

Here's the pull request for slow, fast and block enumeration for DIOSViews. There are some additional changes I made to the Views Service module to support some scenarios. Please let me know where I can place these changes as well.

Cheers, 

Rasputin.

### CODE REVIEW

**Comment by kylebrowning** [comment]
Ill go through all of these changes sometime this weekend, but I can tell you right now, theres a lot of things in there that are very specific and im not very very keen on bringing an extra 10 files.

But it can be very very usefull for sure.

My main issue with most of these commits is all of the Appfliccka stuff that exists in the code.

**Comment by RasputinJones2k** [comment]
Sure thing. Actually I realized this right after making the pull request unfortunately (first time contributing code..). I can make some effort to generalize but let's talk about that after you go though it.

**Comment by RasputinJones2k** [comment]
Hey there. Did you take a look at the code yet. I thought about the problem over the weekend and reckoned that we probably could take out the custom Aflicka stuff by using a singleton to initialize the query builders as opposed to me storing them in the AppDelegate singleton. There are probably a lot of other ways to address this... let me know.

**Comment by kylebrowning** [comment]
I did look at it, im sure I really want to add all of this. Im certainly down to add most of this stuff, but it doesnt need to be subclassed does it? WHy subclass it? Also, The votingApi I dont want to bring into the project b/c it is not a core services resource. I would be happy to start, or have someone start a project that subclasses this one for the needs of other services, but other services I cant really rely on always working. So, if you add all this blocking code to the DIOSViews object, etc I think it would be good.

**Comment by RasputinJones2k** [comment]
Hmm it wasn't subclassed it was encapsulated right? Which part was subclassed? I did use encapsulation for the DIOSViews object  because I wasn't sure at that time I was going to be contributing code back and encapsulation would allow me to pick up changes you made without my code getting broken (fwding design pattern i think...).

Sure I'm happy to look into moving this up to DIOSViews this weekend. Sorry about VotingAPI it shouldn't have been there really. First time mucking around with git so much. I also have subclasses for the Search Service now as well. :) I'll let you know.

**Comment by kylebrowning** [comment]
Ahh you are correct it is encapsulated.but yeah instead of having 8 other more classes, we should just attach the stuff to the original objects and that way nobody is confused as to which classes to instantiate and itll be easier to update the other branches.

**Comment by kylebrowning** [comment]
Open a new pull request when you have made these changes, and ill push them to all other branches.

**Pull request closed without merging**
